# Generated by Django 5.2.3 on 2025-06-28 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_column='numero', default='', max_length=255)),
                ('nome', models.CharField(db_column='nome', default='', max_length=255)),
                ('MM', models.CharField(db_column='MM', default='', max_length=255)),
                ('YY', models.CharField(db_column='YY', default='', max_length=255)),
                ('CVV', models.CharField(db_column='CVV', default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Minuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('conteudo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiao', models.CharField(choices=[('Barlavento', 'Barlavento'), ('Sotavento', 'Sotavento')], max_length=20)),
                ('canal', models.CharField(choices=[('RCV', 'RCV'), ('RCV+', 'RCV+'), ('TCV', 'TCV')], max_length=10)),
                ('horario', models.CharField(choices=[('12:30', '12:30'), ('18:30', '18:30')], max_length=10)),
                ('vezes', models.IntegerField(choices=[(1, '1 vez'), (2, '2 vezes'), (3, '3 vezes'), (4, '4 vezes'), (5, '5 vezes')])),
                ('conteudo', models.TextField()),
                ('valor_total', models.FloatField()),
                ('estado', models.CharField(choices=[('Pendente', 'Pendente'), ('Concluído', 'Concluído')], max_length=20)),
                ('minuta_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.minuta')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.FloatField()),
                ('anuncio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.anuncio')),
                ('cartao_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.cartao')),
            ],
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recibo', models.CharField(max_length=100)),
                ('data_pagamento', models.DateField()),
                ('metodo_pagamento', models.CharField(max_length=50)),
                ('valor', models.FloatField()),
                ('pagamento_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.pagamento')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('perfil_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.perfil')),
            ],
        ),
        migrations.AddField(
            model_name='anuncio',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.user'),
        ),
        migrations.CreateModel(
            name='UserCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.cartao')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
            options={
                'unique_together': {('user_id', 'cartao_id')},
            },
        ),
    ]
