# Generated by Django 5.2.3 on 2025-08-01 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_anuncio_valor_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatura',
            name='valor',
        ),
    ]
