# Generated by Django 5.2.3 on 2025-08-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_fatura_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='nome',
            field=models.CharField(default='sem_nome', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anuncio',
            name='telefone',
            field=models.CharField(default='Anúncio sem nome', max_length=20),
            preserve_default=False,
        ),
    ]
