# Generated by Django 5.2.3 on 2025-08-04 12:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_anuncio_email_anuncio_nome_anuncio_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatura',
            name='data_pagamento',
        ),
        migrations.RemoveField(
            model_name='fatura',
            name='metodo_pagamento',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='data_pagamento',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagamento',
            name='metodo_pagamento',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
