# Generated by Django 5.2.3 on 2025-08-07 10:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_fatura_data_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='data',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
